development:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development
  pool: 5
  username: postgres
  password: postgre

test:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_test
  pool: 5
  username: postgres
  password:  postgre

production:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_production
  pool: 5
  username: postgres
  password: postgre
